export const IMAGES = {
  logo: "/assets/logo.svg",
  arrowLineDown2: "/assets/ArrowLineDown2.svg",
  calendarBlank: "/assets/CalendarBlank.svg",
  caretDown: "/assets/CaretDown.svg",
  group: "/assets/Group.svg",
  image: "/assets/Image.png",
  account: "/assets/Account.png",
  search: "/assets/Search.svg",
  change: "/assets/change.svg",
  message: "/assets/message.svg",
  noti: "/assets/noti.svg",
  setting: "/assets/setting.svg",
  question: "/assets/question.svg",
  downWhite: "/assets/downWhite.svg",
  upGreen: "/assets/upGreen.svg",
  downRed: "/assets/downRed.svg",
  empty: "/assets/empty.png",
};
